
package hidefbilling;


import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Product extends javax.swing.JDialog {
    private int PT_ID;
    private Connection con;
    private PreparedStatement ps;
    private ResultSet rs;
    private int P_ID;

    /**
     * Creates new form Product
     */
    public Product(java.awt.Frame parent, boolean modal,Connection con) {
        super(parent, modal);
        initComponents();
        this.con=con; reset_product();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jTextField51 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jTextField53 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        jTextField54 = new javax.swing.JTextField();
        jButton48 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel72.setText("Product Type");

        jTextField51.setText("jTextField51");
        jTextField51.setNextFocusableComponent(jTextField52);

        jLabel73.setText("Product Name");

        jTextField52.setText("jTextField52");
        jTextField52.setNextFocusableComponent(jTextField53);

        jLabel74.setText("Product Code");

        jTextField53.setText("jTextField53");
        jTextField53.setNextFocusableComponent(jButton38);

        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S. No.", "Product Name", "Product Code", "Product Type"
            }
        ));
        jTable8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable8MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jTable8);
        if (jTable8.getColumnModel().getColumnCount() > 0) {
            jTable8.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTable8.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jButton38.setText("Add");
        jButton38.setNextFocusableComponent(jButton39);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jButton38.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton38KeyPressed(evt);
            }
        });

        jButton39.setText("Update");
        jButton39.setNextFocusableComponent(jButton40);
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jButton39.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton39KeyPressed(evt);
            }
        });

        jButton40.setText("Delete");
        jButton40.setNextFocusableComponent(jButton48);
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jButton40.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton40KeyPressed(evt);
            }
        });

        jLabel75.setText("Search");

        jTextField54.setText("jTextField54");
        jTextField54.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField54KeyReleased(evt);
            }
        });

        jButton48.setText("Reset");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jButton48.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton48KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel74, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel73, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jLabel72, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField52, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jTextField51)
                            .addComponent(jTextField53)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButton40)
                        .addGap(18, 18, 18)
                        .addComponent(jButton48)))
                .addGap(10, 10, 10)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField54))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75)
                    .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73)
                            .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel74)
                            .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton38)
                            .addComponent(jButton39)
                            .addComponent(jButton40)
                            .addComponent(jButton48)))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        product_insert();
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jTextField54KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField54KeyReleased
        // TODO add your handling code here:
        new MainFrame(null).getTableData("SELECT P_NAME,P_CODE,PT_NAME FROM PRODUCT INNER JOIN PRODUCT_TYPE ON P_PT_ID=PT_ID WHERE P_NAME LIKE '%"+jTextField54.getText()+"%'", jTable8);
    }//GEN-LAST:event_jTextField54KeyReleased

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        // TODO add your handling code here:
        reset_product();
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        product_update();
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton38KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton38KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)product_insert();
    }//GEN-LAST:event_jButton38KeyPressed

    private void jButton39KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton39KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)product_update();
    }//GEN-LAST:event_jButton39KeyPressed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        product_remove();
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton40KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton40KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)product_remove();
    }//GEN-LAST:event_jButton40KeyPressed

    private void jButton48KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton48KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)reset_product();
    }//GEN-LAST:event_jButton48KeyPressed

    private void jTable8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable8MouseClicked
        // TODO add your handling code here:
         if(jTable8.getSelectedRow()!=-1){
            P_ID=Integer.parseInt(jTable8.getValueAt(jTable8.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_jTable8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Product dialog = new Product(new javax.swing.JFrame(), true, new DBConnection().dbConnection("hidefDB"));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton48;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JTable jTable8;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    // End of variables declaration//GEN-END:variables
protected void reset_product(){
    jTextField51.setText("");
    jTextField52.setText(MainFrame.P_NAME);
    jTextField53.setText("");
    jTextField54.setText("");
    P_ID=0;
   getTableData("SELECT P_ID,P_NAME,P_CODE,PT_NAME FROM PRODUCT INNER JOIN PRODUCT_TYPE ON P_PT_ID=PT_ID", jTable8);
}
public void getTableData(String query,javax.swing.JTable table){
    DefaultTableModel dtm=(DefaultTableModel)table.getModel();
    for(int i=dtm.getRowCount()-1;i>=0;i--)
        dtm.removeRow(i);
    try{ ps=con.prepareStatement(query);
        rs=ps.executeQuery();
     ResultSetMetaData   rsmd=rs.getMetaData();
        LinkedList<String> s=new LinkedList<String>();
            while(rs.next()){
                for(int i=1;i<=rsmd.getColumnCount();i++){      
                s.add(rs.getString(i));}
                Object[] o=s.toArray();
                dtm.addRow(o);
                s.clear();
            }      
    }catch(SQLException e){
          JOptionPane.showMessageDialog(null, e);
    }
}
protected void product_insert(){
     try{ PT_ID=0;
            if(!jTextField51.getText().isEmpty()){
                ps=con.prepareStatement("SELECT * FROM PRODUCT_TYPE WHERE PT_NAME='"+jTextField51.getText()+"'");
                rs=ps.executeQuery();
                if(!rs.next()){
                    ps=con.prepareStatement("INSERT INTO PRODUCT_TYPE(PT_NAME) VALUES(?)");
                    ps.setString(1, jTextField51.getText());
                    ps.executeUpdate();
                }
                ps=con.prepareStatement("SELECT PT_ID FROM PRODUCT_TYPE WHERE PT_NAME='"+jTextField51.getText()+"'");
                rs=ps.executeQuery();
                if(rs.next())PT_ID=rs.getInt(1);
            }
            if(!jTextField51.getText().isEmpty() && !jTextField52.getText().isEmpty()){
                ps=con.prepareStatement("INSERT INTO PRODUCT(P_NAME,P_CODE,P_PT_ID) VALUES(?,?,?)");
                ps.setString(1, jTextField52.getText());
                ps.setString(2, jTextField53.getText());
                ps.setInt(3, PT_ID);
                ps.executeUpdate();
               
                if(JOptionPane.showConfirmDialog (null, "Data Inserted, Do you want to Close ?","Warning",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                this.dispose();
                }
                
            }
            reset_product();
            
        }catch(Exception e){e.printStackTrace();}
 }
protected void product_update(){
try{ P_ID=0;ps=con.prepareStatement("SELECT P_ID FROM PRODUCT WHERE P_NAME='"+jTextField52.getText()+"'");
     rs=ps.executeQuery();
     if(rs.next())
         P_ID=rs.getInt(1);
    ps=con.prepareStatement("UPDATE PRODUCT SET P_NAME=?, P_CODE=? WHERE P_ID="+P_ID);
             ps.setString(1, jTextField52.getText());
             ps.setString(2, jTextField53.getText());
             ps.executeUpdate();
             reset_product();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
}
protected void product_remove(){
    try{P_ID=0;ps=con.prepareStatement("SELECT P_ID FROM PRODUCT WHERE P_NAME='"+jTextField52.getText()+"'");
        rs=ps.executeQuery();
        if(rs.next())
         P_ID=rs.getInt(1);
        ps=con.prepareStatement("DELETE FROM PRODUCT WHERE P_ID="+P_ID);
            ps.execute();
             reset_product();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
}
}
